// post thread
export const POST_THREAD_REQUEST = 'POST_THREAD_REQUEST';
export const POST_THREAD_SUCCESS = 'POST_THREAD_SUCCESS';
export const POST_THREAD_FAIL = 'POST_THREAD_FAIL';

// list thread
export const LIST_THREAD_REQUEST = 'LIST_THREAD_REQUEST';
export const LIST_THREAD_SUCCESS = 'LIST_THREAD_SUCCESS';
export const LIST_THREAD_FAIL = 'LIST_THREAD_FAIL';
export const LIST_THREAD_RESET = 'LIST_THREAD_RESET';

// thread category
export const LIST_CATEGORY_REQUEST = 'LIST_CATEGORY_REQUEST';
export const LIST_CATEGORY_SUCCESS = 'LIST_CATEGORY_SUCCESS';
export const LIST_CATEGORY_FAIL = 'LIST_CATEGORY_FAIL';

// get a thread answers
export const LIST_THREAD_ANSWERS_REQUEST = 'LIST_THREAD_ANSWERS_REQUEST';
export const LIST_THREAD_ANSWERS_SUCCESS = 'LIST_THREAD_ANSWERS_SUCCESS';
export const LIST_THREAD_ANSWERS_FAIL = 'LIST_THREAD_ANSWERS_FAIL';

// get innter thread answers
export const LIST_THREAD_INNER_ANSWERS_REQUEST = 'LIST_THREAD_INNER_ANSWERS_REQUEST';
export const LIST_THREAD_INNER_ANSWERS_SUCCESS = 'LIST_THREAD_INNER_ANSWERS_SUCCESS';
export const LIST_THREAD_INNER_ANSWERS_FAIL = 'LIST_THREAD_INNER_ANSWERS_FAIL';

// answer a thread 
export const ANSWER_THREAD_REQUEST = 'ANSWER_THREAD_REQUEST';
export const ANSWER_THREAD_SUCCESS = 'ANSWER_THREAD_SUCCESS';
export const ANSWER_THREAD_FAIL = 'ANSWER_THREAD_FAIL';
export const ANSWER_THREAD_RESET = 'ANSWER_THREAD_RESET';